Document: mysql-hyperloglog
Title: Debian mysql-hyperloglog Manual
Author: <insert document author here>
Abstract: This manual describes what mysql-hyperloglog is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mysql-hyperloglog/mysql-hyperloglog.sgml.gz

Format: postscript
Files: /usr/share/doc/mysql-hyperloglog/mysql-hyperloglog.ps.gz

Format: text
Files: /usr/share/doc/mysql-hyperloglog/mysql-hyperloglog.text.gz

Format: HTML
Index: /usr/share/doc/mysql-hyperloglog/html/index.html
Files: /usr/share/doc/mysql-hyperloglog/html/*.html
